### ISSUE TITLE
Tv Tokyo Not Working 

### ISSUE THREAD

**Issue by snivy21** [luongz/iptv-jp#124]
Actually...Till today's afternoon the source was working fine but now it is not working showing ig some server can't reach idk if it's in maintanence but I really need a source till friday! So if you fixed it would be much better I really liked it because it had less issues and works smooth! I request to the owner to fix it
![Screenshot_2024-11-13-18-14-51-40_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/40c4e25a-761c-40c5-a393-9365f2050583)

**Comment by makimaki69** [comment]
Not only recently, but "vthanh" has been customary for the owner to take down the server about once a week (mainly on weekends) for maintenance.

"vthanh" is the nonprofit private server by the owner, not a commercial (=taking a rate out of an audience a premise) delivery server. It will always prevent you from thinking that it is natural to be able to access it in a stable, good state.

Instead of complaining to the owner that you can't watch the stream as much as you would like, shouldn't you say thank you to the owner for keeping the "vthanh"stream?
