### ISSUE TITLE
Optimize the EPG script

### ISSUE THREAD

**Issue by weldon1045** [luongz/iptv-jp#84]
Hey, luongz, I have noticed way before you had issues with the EPG host that, sometimes, some EPG information would load only for some channels, while for others it wouldn't load anything. And, I think the main issue lies on how many channels does your script load.

According to an IPTV client, your EPG has information for 182 channels, each of them having programs for almost the rest of the week, compared to the 84 channels actually using that information. More than the other half is not being used.

So, I think it would be great if you could only filter the EPG for those channels that are necessary, then, if a new channel is added, you just add it to the filter.

This could improve EPG loading times and avoid this condition of leaving out information of necessary channels that might be occupied by information of channels not being used currently.

**Comment by luongz** [comment]
> Some EPG information would load only for some channels, while for others it wouldn't load anything.

I have completed editing the script and started enabling Grabber at 2:15 AM (GMT +7), now is 9:05 AM, and Grabber still running (240/244 channels). Maybe since it was just launched, it probably hasn't finished collecting channels yet.
At the moment you can see that all the channels in the list have EPG data.

> So, I think it would be great if you could only filter the EPG for those channels that are necessary, then, if a new channel is added, you just add it to the filter.

Maybe I will consider it. I don't have much time, but I will plan soon.
